### ISSUE TITLE
Update Rollbar JS snippet from 1.1 to 1.4

### ISSUE THREAD

**Issue by wcjohnson11** [segment-integrations/analytics.js-integration-rollbar#1]
https://github.com/segment-integrations/analytics.js-integration-rollbar/blob/master/lib/index.js#L36

The current version of Rollbar we're loading is V1.1 via the snippet above. We should update that to 1.4, the latest version to take advantage of Bug Fixes and Improvements.

via Jeff Sinclar, Atlassian

[Rollbar JS documentation](https://rollbar.com/docs/notifier/rollbar.js/)
[Rollbar GH repo](https://github.com/rollbar/rollbar.js)

**Comment by hankim813** [comment]
fixed in https://github.com/segment-integrations/analytics.js-integration-rollbar/pull/4
